config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :tasks, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    member do
      put 'mark'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :title

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks.where(done: false)
  end

  def destroy
    @tasks = Task.find_by(id: params[:id])
    @tasks.destroy
    redirect_to root_url
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end

  def update
    @task = Task.update(params[:id], task_params)
    redirect_to root_url
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      redirect_to @task, notice: 'Task created'
    else
      render :new
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def mark
    @task = Task.find_by(id: params[:id])
    @task.update(done: true)
    redirect_to root_url, notice: 'Marked as done'
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :description,
      :due_date
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header_navbar' %>
    <div class="container">
      <div class="row">
        <%= content_tag :p, flash[:notice] %>
        <%= content_tag :p, flash[:alert] %>
        <%= content_tag :p, notice %>
        <%= content_tag :p, alert %>
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_header_navbar.html.erb
<div class="row">
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <%= link_to 'Logo', root_path, { class: 'brand-logo' } %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <%= link_to 'New task', new_task_path %>
          </li>
          <li><a href="badges.html">Components</a></li>
          <li><a href="collapsible.html">Javascript</a></li>
          <li><a href="mobile.html">Mobile</a></li>
          <li><%= link_to_if(current_user, 'Log out', { controller: 'devise/sessions', action: 'destroy' }, { method: :delete }) %></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li>
            <%= link_to 'New task', new_task_path %>
          </li>
          <li><a href="badges.html">Components</a></li>
          <li><a href="collapsible.html">Javascript</a></li>
          <li><a href="mobile.html">Mobile</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <%= simple_form_for task do |f| %>
    <div class="row">
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :due_date, as: :string, input_html: { type: 'date', class: 'datepicker' } %>
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/tasks/_tasks.html.erb
<div class="col s12 m12">
  <%= content_tag :ul, class: 'tasks' do %>
    <% @tasks.each do |task| %>
      <%= content_tag :li, class: 'col s12 m6' do %>
        <div class="card">
          <div class="card-content">
            <%= content_tag :span, class: 'card-title activator grey-text text-darken-4' do %>
              <%= task.title %>
              <%= content_tag :i, 'more_vert', class: 'material-icons right' unless task.description.nil? %>
            <% end %>
            <%= content_tag :p, "Due date: #{task.due_date}" unless task.due_date.nil? %>
          </div>
          <%= content_tag :div, class: 'card-reveal' do %>
            <%= content_tag :span, class: 'card-title grey-text text-darken-4' do %>
              <i class="material-icons right">close</i>
            <% end %>
            <%= content_tag :p, task.description %>
            <% end unless task.description.nil? %>
            <div class="card-action">
              <%= content_tag :p, link_to('Mark as done', mark_task_path(task), { method: :put }) %>
              <%= content_tag :p do %>
                <%= link_to 'Edit task', edit_task_path(task) %>
              <% end %>
              <%= content_tag :p do %>
                <%= link_to 'Delete', task, { method: :delete } %>
              <% end %>
            </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render partial: 'form', locals: { task: @task } %>

app/views/tasks/index.html.erb
<%= render 'tasks' %>

app/views/tasks/new.html.erb
<%= render partial: 'form', locals: { task: @task } %>